---
- name: "download terraform binary {{ terraform_version }}"
  get_url:
      url: "{{ terraform_base_url }}/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
      dest: /tmp/terraform_{{ terraform_version }}.zip
      mode: 0644
  when: terraform_current_version != terraform_version

- name: extract terraform binary
  unarchive:
    src: /tmp/terraform_{{ terraform_version }}.zip
    dest: /usr/local/bin/
    mode: 0755
  when: terraform_current_version != terraform_version
